name: neural_network
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.0-403.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  ml_linalg: ^13.11.30
  provider: ^6.0.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
